##项目上下文路径，端口号
server:
  servlet:
    context-path: /showpage
  port: 8081

##连接数据库
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin
    url: jdbc:mysql://localhost:3306/showpage?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    # 连接超时时间（毫秒）
    timeout: 1000
    jedis:
      pool:
        #  连接池最大连接数
        max-active: 8
        #  连接池最大阻塞等待时间（负值表示没有限制）
        max-wait: -1
        #  连接池最大空闲连接
        max-idle: 8
        #  连接池最小空闲连接
        min-idl: 0






#下面这些内容是为了让MyBatis映射
#指定Mybatis的Mapper文件
#指定Mybatis的实体目录

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.myshowpage.pojo




